//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneOrdiniService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/GestioneOrdini_CORE.Models")]
    public partial class Cliente : object
    {
        
        private string CodiceClienteField;
        
        private string CognomeField;
        
        private int IdField;
        
        private string NomeField;
        
        private System.Collections.Generic.List<GestioneOrdiniService.Ordine> OrdiniField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceCliente
        {
            get
            {
                return this.CodiceClienteField;
            }
            set
            {
                this.CodiceClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome
        {
            get
            {
                return this.CognomeField;
            }
            set
            {
                this.CognomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<GestioneOrdiniService.Ordine> Ordini
        {
            get
            {
                return this.OrdiniField;
            }
            set
            {
                this.OrdiniField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordine", Namespace="http://schemas.datacontract.org/2004/07/GestioneOrdini_CORE.Models")]
    public partial class Ordine : object
    {
        
        private GestioneOrdiniService.Cliente ClienteField;
        
        private string CodiceOrdineField;
        
        private string CodiceProdottoField;
        
        private System.DateTime DataOrdineField;
        
        private int IdField;
        
        private System.Nullable<int> IdClienteField;
        
        private decimal ImportoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestioneOrdiniService.Cliente Cliente
        {
            get
            {
                return this.ClienteField;
            }
            set
            {
                this.ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceOrdine
        {
            get
            {
                return this.CodiceOrdineField;
            }
            set
            {
                this.CodiceOrdineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceProdotto
        {
            get
            {
                return this.CodiceProdottoField;
            }
            set
            {
                this.CodiceProdottoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataOrdine
        {
            get
            {
                return this.DataOrdineField;
            }
            set
            {
                this.DataOrdineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importo
        {
            get
            {
                return this.ImportoField;
            }
            set
            {
                this.ImportoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestioneOrdiniService.IClienteService")]
    public interface IClienteService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetAllClienti", ReplyAction="http://tempuri.org/IClienteService/GetAllClientiResponse")]
        System.Collections.Generic.List<GestioneOrdiniService.Cliente> GetAllClienti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetAllClienti", ReplyAction="http://tempuri.org/IClienteService/GetAllClientiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GestioneOrdiniService.Cliente>> GetAllClientiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CreateCliente", ReplyAction="http://tempuri.org/IClienteService/CreateClienteResponse")]
        bool CreateCliente(GestioneOrdiniService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CreateCliente", ReplyAction="http://tempuri.org/IClienteService/CreateClienteResponse")]
        System.Threading.Tasks.Task<bool> CreateClienteAsync(GestioneOrdiniService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DeleteClienteById", ReplyAction="http://tempuri.org/IClienteService/DeleteClienteByIdResponse")]
        bool DeleteClienteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DeleteClienteById", ReplyAction="http://tempuri.org/IClienteService/DeleteClienteByIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteClienteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/UpdateCliente", ReplyAction="http://tempuri.org/IClienteService/UpdateClienteResponse")]
        bool UpdateCliente(GestioneOrdiniService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/UpdateCliente", ReplyAction="http://tempuri.org/IClienteService/UpdateClienteResponse")]
        System.Threading.Tasks.Task<bool> UpdateClienteAsync(GestioneOrdiniService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteById", ReplyAction="http://tempuri.org/IClienteService/GetClienteByIdResponse")]
        GestioneOrdiniService.Cliente GetClienteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteById", ReplyAction="http://tempuri.org/IClienteService/GetClienteByIdResponse")]
        System.Threading.Tasks.Task<GestioneOrdiniService.Cliente> GetClienteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IClienteServiceChannel : GestioneOrdiniService.IClienteService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<GestioneOrdiniService.IClienteService>, GestioneOrdiniService.IClienteService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClienteServiceClient() : 
                base(ClienteServiceClient.GetDefaultBinding(), ClienteServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IClienteService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ClienteServiceClient.GetBindingForEndpoint(endpointConfiguration), ClienteServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClienteServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClienteServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<GestioneOrdiniService.Cliente> GetAllClienti()
        {
            return base.Channel.GetAllClienti();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GestioneOrdiniService.Cliente>> GetAllClientiAsync()
        {
            return base.Channel.GetAllClientiAsync();
        }
        
        public bool CreateCliente(GestioneOrdiniService.Cliente cliente)
        {
            return base.Channel.CreateCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> CreateClienteAsync(GestioneOrdiniService.Cliente cliente)
        {
            return base.Channel.CreateClienteAsync(cliente);
        }
        
        public bool DeleteClienteById(int id)
        {
            return base.Channel.DeleteClienteById(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClienteByIdAsync(int id)
        {
            return base.Channel.DeleteClienteByIdAsync(id);
        }
        
        public bool UpdateCliente(GestioneOrdiniService.Cliente cliente)
        {
            return base.Channel.UpdateCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClienteAsync(GestioneOrdiniService.Cliente cliente)
        {
            return base.Channel.UpdateClienteAsync(cliente);
        }
        
        public GestioneOrdiniService.Cliente GetClienteById(int id)
        {
            return base.Channel.GetClienteById(id);
        }
        
        public System.Threading.Tasks.Task<GestioneOrdiniService.Cliente> GetClienteByIdAsync(int id)
        {
            return base.Channel.GetClienteByIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IClienteService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IClienteService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/GestioneOrdini_WCFService/ClienteServ" +
                        "ice/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClienteServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IClienteService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClienteServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IClienteService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IClienteService,
        }
    }
}
